// Static catalog of the public PNG collection. Keep paths in sync with public/emoji-icons/.
export interface EmojiOption {
  value: string;
  label: string;
  category: string;
}

export type EmojiKind = "profile" | "other";

export const EMOJI_CATEGORIES = {
  "profile-pic": "Profile pictures",
  activities: "Activities",
  "food-and-drinks": "Food & drinks",
  objects: "Objects",
  "travel-and-places": "Travel & places",
} as const;

const EMOJI_PATHS = [
  "activities/admission-tickets-3d.png",
  "activities/american-football-3d.png",
  "activities/artist-palette-3d.png",
  "activities/badminton-3d.png",
  "activities/balloon-3d.png",
  "activities/basketball-3d.png",
  "activities/bowling-3d.png",
  "activities/boxing-glove-3d.png",
  "activities/bullseye-3d.png",
  "activities/christmas-tree-3d.png",
  "activities/confetti-ball-3d.png",
  "activities/cricket-game-3d.png",
  "activities/crystal-ball-3d.png",
  "activities/field-hockey-3d.png",
  "activities/firecracker-3d.png",
  "activities/fireworks-3d.png",
  "activities/japanese-dolls-3d.png",
  "activities/joystick-3d.png",
  "activities/kite-3d.png",
  "activities/mirror-ball-3d.png",
  "activities/nazar-amulet-3d.png",
  "activities/party-popper-3d.png",
  "activities/ping-pong-3d.png",
  "activities/pool-8-ball-3d.png",
  "activities/ribbon-3d.png",
  "activities/soccer-ball-3d.png",
  "activities/sparkles-3d.png",
  "activities/ticket-3d.png",
  "activities/video-game-3d.png",
  "activities/volleyball-3d.png",
  "food-and-drinks/bacon-3d.png",
  "food-and-drinks/baguette-bread-3d.png",
  "food-and-drinks/banana-3d.png",
  "food-and-drinks/beans-3d.png",
  "food-and-drinks/beer-mug-3d.png",
  "food-and-drinks/birthday-cake-3d.png",
  "food-and-drinks/bottle-with-popping-cork-3d.png",
  "food-and-drinks/bread-3d.png",
  "food-and-drinks/broccoli-3d.png",
  "food-and-drinks/bubble-tea-3d.png",
  "food-and-drinks/butter-3d.png",
  "food-and-drinks/candy-3d.png",
  "food-and-drinks/canned-food-3d.png",
  "food-and-drinks/carrot-3d.png",
  "food-and-drinks/cheese-wedge-3d.png",
  "food-and-drinks/cherries-3d.png",
  "food-and-drinks/chocolate-bar-3d.png",
  "food-and-drinks/clinking-beer-mugs-3d.png",
  "food-and-drinks/cocktail-glass-3d.png",
  "food-and-drinks/coconut-3d.png",
  "food-and-drinks/cookie-3d.png",
  "food-and-drinks/crab-3d.png",
  "food-and-drinks/croissant-3d.png",
  "food-and-drinks/cup-with-straw-3d.png",
  "food-and-drinks/cupcake-3d.png",
  "food-and-drinks/curry-rice-3d.png",
  "food-and-drinks/doughnut-3d.png",
  "food-and-drinks/ear-of-corn-3d.png",
  "food-and-drinks/egg-3d.png",
  "food-and-drinks/eggplant-3d.png",
  "food-and-drinks/fork-and-knife-with-plate-3d.png",
  "food-and-drinks/french-fries-3d.png",
  "food-and-drinks/ginger-root-3d.png",
  "food-and-drinks/grapes-3d.png",
  "food-and-drinks/green-apple-3d.png",
  "food-and-drinks/green-salad-3d.png",
  "food-and-drinks/hamburger-3d.png",
  "food-and-drinks/hot-beverage-3d.png",
  "food-and-drinks/hot-dog-3d.png",
  "food-and-drinks/hot-pepper-3d.png",
  "food-and-drinks/ice-3d.png",
  "food-and-drinks/kitchen-knife-3d.png",
  "food-and-drinks/lime-3d.png",
  "food-and-drinks/lobster-3d.png",
  "food-and-drinks/lollipop-3d.png",
  "food-and-drinks/mushroom-3d.png",
  "food-and-drinks/pancakes-3d.png",
  "food-and-drinks/peach-3d.png",
  "food-and-drinks/pear-3d.png",
  "food-and-drinks/pizza-3d.png",
  "food-and-drinks/popcorn-3d.png",
  "food-and-drinks/poultry-leg-3d.png",
  "food-and-drinks/red-apple-3d.png",
  "food-and-drinks/salt-3d.png",
  "food-and-drinks/sandwich-3d.png",
  "food-and-drinks/shallow-pan-of-food-3d.png",
  "food-and-drinks/shortcake-3d.png",
  "food-and-drinks/shrimp-3d.png",
  "food-and-drinks/soft-ice-cream-3d.png",
  "food-and-drinks/steaming-bowl-3d.png",
  "food-and-drinks/strawberry-3d.png",
  "food-and-drinks/teacup-without-handle-3d.png",
  "food-and-drinks/tropical-drink-3d.png",
  "food-and-drinks/watermelon-3d.png",
  "food-and-drinks/wine-glass-3d.png",
  "objects/bathtub-3d.png",
  "objects/bikini-3d.png",
  "objects/bookmark-tabs-3d.png",
  "objects/books-3d.png",
  "objects/broom-3d.png",
  "objects/calendar-3d.png",
  "objects/camera-3d.png",
  "objects/chart-decreasing-3d.png",
  "objects/chart-increasing-3d.png",
  "objects/cigarette-3d.png",
  "objects/clapper-board-3d.png",
  "objects/clipboard-3d.png",
  "objects/coat-3d.png",
  "objects/credit-card-3d.png",
  "objects/desktop-computer-3d.png",
  "objects/dress-3d.png",
  "objects/fire-extinguisher-3d.png",
  "objects/flashlight-3d.png",
  "objects/flute-3d.png",
  "objects/fountain-pen-3d.png",
  "objects/gear-3d.png",
  "objects/gem-stone-3d.png",
  "objects/graduation-cap-3d.png",
  "objects/hammer-and-wrench-3d.png",
  "objects/headphone-3d.png",
  "objects/ledger-3d.png",
  "objects/light-bulb-3d.png",
  "objects/lipstick-3d.png",
  "objects/locked-3d.png",
  "objects/locked-with-key-3d.png",
  "objects/loudspeaker-3d.png",
  "objects/magnifying-glass-tilted-right-3d.png",
  "objects/microphone-3d.png",
  "objects/mirror-3d.png",
  "objects/moai-3d.png",
  "objects/mobile-phone-3d.png",
  "objects/money-bag-3d.png",
  "objects/movie-camera-3d.png",
  "objects/musical-notes-3d.png",
  "objects/musical-score-3d.png",
  "objects/nut-and-bolt-3d.png",
  "objects/one-piece-swimsuit-3d.png",
  "objects/package-3d.png",
  "objects/page-facing-up-3d.png",
  "objects/paperclip-3d.png",
  "objects/pill-3d.png",
  "objects/plunger-3d.png",
  "objects/printer-3d.png",
  "objects/radio-3d.png",
  "objects/ring-3d.png",
  "objects/roll-of-paper-3d.png",
  "objects/rolled-up-newspaper-3d.png",
  "objects/running-shoe-3d.png",
  "objects/scissors-3d.png",
  "objects/screwdriver-3d.png",
  "objects/shield-3d.png",
  "objects/shopping-bags-3d.png",
  "objects/shopping-cart-3d.png",
  "objects/shower-3d.png",
  "objects/spiral-calendar-3d.png",
  "objects/stethoscope-3d.png",
  "objects/studio-microphone-3d.png",
  "objects/sunglasses-3d.png",
  "objects/syringe-3d.png",
  "objects/telephone-3d.png",
  "objects/toilet-3d.png",
  "objects/toothbrush-3d.png",
  "objects/top-hat-3d.png",
  "objects/violin-3d.png",
  "objects/womans-hat-3d.png",
  "profile-pic/alien-3d.png",
  "profile-pic/alien-monster-3d.png",
  "profile-pic/ant-3d.png",
  "profile-pic/artist-3d-default.png",
  "profile-pic/astronaut-3d-default.png",
  "profile-pic/basketball-3d.png",
  "profile-pic/bat-3d.png",
  "profile-pic/bear-3d.png",
  "profile-pic/bird-3d.png",
  "profile-pic/bison-3d.png",
  "profile-pic/blackbird-3d.png",
  "profile-pic/blossom-3d.png",
  "profile-pic/bomb-3d.png",
  "profile-pic/bug-3d.png",
  "profile-pic/butterfly-3d.png",
  "profile-pic/cactus-3d.png",
  "profile-pic/camel-3d.png",
  "profile-pic/cat-face-3d.png",
  "profile-pic/chicken-3d.png",
  "profile-pic/clown-face-3d.png",
  "profile-pic/cockroach-3d.png",
  "profile-pic/construction-worker-3d-default.png",
  "profile-pic/cook-3d-default.png",
  "profile-pic/cow-face-3d.png",
  "profile-pic/cowboy-hat-face-3d.png",
  "profile-pic/crocodile-3d.png",
  "profile-pic/deciduous-tree-3d.png",
  "profile-pic/detective-3d-default.png",
  "profile-pic/dog-face-3d.png",
  "profile-pic/dolphin-3d.png",
  "profile-pic/duck-3d.png",
  "profile-pic/elephant-3d.png",
  "profile-pic/evergreen-tree-3d.png",
  "profile-pic/eyes-3d.png",
  "profile-pic/farmer-3d-default.png",
  "profile-pic/feather-3d.png",
  "profile-pic/firefighter-3d-default.png",
  "profile-pic/fish-3d.png",
  "profile-pic/flamingo-3d.png",
  "profile-pic/fly-3d.png",
  "profile-pic/footprints-3d.png",
  "profile-pic/four-leaf-clover-3d.png",
  "profile-pic/fox-3d.png",
  "profile-pic/frog-3d.png",
  "profile-pic/front-facing-baby-chick-3d.png",
  "profile-pic/ghost-3d.png",
  "profile-pic/goblin-3d.png",
  "profile-pic/hatching-chick-3d.png",
  "profile-pic/herb-3d.png",
  "profile-pic/hippopotamus-3d.png",
  "profile-pic/horse-face-3d.png",
  "profile-pic/jack-o-lantern-3d.png",
  "profile-pic/jellyfish-3d.png",
  "profile-pic/koala-3d.png",
  "profile-pic/lady-beetle-3d.png",
  "profile-pic/lion-3d.png",
  "profile-pic/lizard-3d.png",
  "profile-pic/man-bald-3d-default.png",
  "profile-pic/man-beard-3d-default.png",
  "profile-pic/man-health-worker-3d-default.png",
  "profile-pic/man-mage-3d-default.png",
  "profile-pic/man-pilot-3d-default.png",
  "profile-pic/man-police-officer-3d-default.png",
  "profile-pic/man-student-3d-default.png",
  "profile-pic/man-superhero-3d-default.png",
  "profile-pic/man-supervillain-3d-default.png",
  "profile-pic/man-technologist-3d-default.png",
  "profile-pic/man-vampire-3d-default.png",
  "profile-pic/man-white-hair-3d-default.png",
  "profile-pic/man-with-veil-3d-default.png",
  "profile-pic/man-zombie-3d.png",
  "profile-pic/maple-leaf-3d.png",
  "profile-pic/microbe-3d.png",
  "profile-pic/moai-3d.png",
  "profile-pic/monkey-face-3d.png",
  "profile-pic/mouse-face-3d.png",
  "profile-pic/nazar-amulet-3d.png",
  "profile-pic/ninja-3d-default.png",
  "profile-pic/orangutan-3d.png",
  "profile-pic/owl-3d.png",
  "profile-pic/palm-tree-3d.png",
  "profile-pic/panda-3d.png",
  "profile-pic/parrot-3d.png",
  "profile-pic/peacock-3d.png",
  "profile-pic/penguin-3d.png",
  "profile-pic/person-curly-hair-3d-default.png",
  "profile-pic/phoenix-bird-3d.png",
  "profile-pic/pig-face-3d.png",
  "profile-pic/pile-of-poo-3d.png",
  "profile-pic/potted-plant-3d.png",
  "profile-pic/prince-3d-default.png",
  "profile-pic/princess-3d-default.png",
  "profile-pic/rabbit-face-3d.png",
  "profile-pic/raccoon-3d.png",
  "profile-pic/rat-3d.png",
  "profile-pic/robot-3d.png",
  "profile-pic/rose-3d.png",
  "profile-pic/rosette-3d.png",
  "profile-pic/santa-claus-3d-default.png",
  "profile-pic/scorpion-3d.png",
  "profile-pic/seal-3d.png",
  "profile-pic/shark-3d.png",
  "profile-pic/skull-3d.png",
  "profile-pic/sloth-3d.png",
  "profile-pic/smiling-face-with-horns-3d.png",
  "profile-pic/snail-3d.png",
  "profile-pic/snowman-3d.png",
  "profile-pic/soccer-ball-3d.png",
  "profile-pic/spider-3d.png",
  "profile-pic/spouting-whale-3d.png",
  "profile-pic/sun-with-face-3d.png",
  "profile-pic/sunflower-3d.png",
  "profile-pic/t-rex-3d.png",
  "profile-pic/teddy-bear-3d.png",
  "profile-pic/tiger-face-3d.png",
  "profile-pic/tulip-3d.png",
  "profile-pic/turtle-3d.png",
  "profile-pic/unicorn-3d.png",
  "profile-pic/whale-3d.png",
  "profile-pic/wolf-3d.png",
  "profile-pic/woman-construction-worker-3d-default.png",
  "profile-pic/woman-cook-3d-default.png",
  "profile-pic/woman-curly-hair-3d-default.png",
  "profile-pic/woman-teacher-3d-default.png",
  "profile-pic/woman-with-headscarf-3d-default.png",
  "profile-pic/woman-zombie-3d.png",
  "profile-pic/wrapped-gift-3d.png",
  "travel-and-places/airplane-3d.png",
  "travel-and-places/ambulance-3d.png",
  "travel-and-places/articulated-lorry-3d.png",
  "travel-and-places/auto-rickshaw-3d.png",
  "travel-and-places/automobile-3d.png",
  "travel-and-places/beach-with-umbrella-3d.png",
  "travel-and-places/bicycle-3d.png",
  "travel-and-places/bridge-at-night-3d.png",
  "travel-and-places/bullet-train-3d.png",
  "travel-and-places/camping-3d.png",
  "travel-and-places/canoe-3d.png",
  "travel-and-places/church-3d.png",
  "travel-and-places/cityscape-3d.png",
  "travel-and-places/construction-3d.png",
  "travel-and-places/desert-3d.png",
  "travel-and-places/desert-island-3d.png",
  "travel-and-places/droplet-3d.png",
  "travel-and-places/ferris-wheel-3d.png",
  "travel-and-places/ferry-3d.png",
  "travel-and-places/globe-showing-europe-africa-3d.png",
  "travel-and-places/globe-with-meridians-3d.png",
  "travel-and-places/glowing-star-3d.png",
  "travel-and-places/helicopter-3d.png",
  "travel-and-places/hospital-3d.png",
  "travel-and-places/hotel-3d.png",
  "travel-and-places/house-with-garden-3d.png",
  "travel-and-places/luggage-3d.png",
  "travel-and-places/motorway-3d.png",
  "travel-and-places/mountain-3d.png",
  "travel-and-places/office-building-3d.png",
  "travel-and-places/rocket-3d.png",
  "travel-and-places/umbrella-with-rain-drops-3d.png",
  "travel-and-places/water-wave-3d.png",
] as const;

export const EMOJI_CATALOG: EmojiOption[] = EMOJI_PATHS.map((value) => {
  const [category, file] = value.split("/");
  const label = file.replace(/-3d(?:-default)?\.png$/, "").replaceAll("-", " ");
  return { value, label: label[0].toUpperCase() + label.slice(1), category };
});

export const PROFILE_EMOJIS = EMOJI_CATALOG.filter((item) => item.category === "profile-pic");
export const OTHER_EMOJIS = EMOJI_CATALOG.filter((item) => item.category !== "profile-pic");

export const DEFAULT_PROFILE_EMOJI = "profile-pic/fox-3d.png";
export const DEFAULT_OTHER_EMOJI = "travel-and-places/airplane-3d.png";
export const DEFAULT_CATEGORY_EMOJI = "food-and-drinks/hamburger-3d.png";

const PROFILE_VALUES = new Set(PROFILE_EMOJIS.map((item) => item.value));
const OTHER_VALUES = new Set(OTHER_EMOJIS.map((item) => item.value));

// Development-era category values still in local IndexedDB render as PNGs without rewriting data.
const LEGACY_CATEGORY_IMAGES: Record<string, string> = {
  "🍔": "food-and-drinks/hamburger-3d.png",
  "🥦": "food-and-drinks/broccoli-3d.png",
  "🚗": "travel-and-places/automobile-3d.png",
  "🏠": "travel-and-places/house-with-garden-3d.png",
  "🎬": "objects/clapper-board-3d.png",
  "🛒": "objects/shopping-cart-3d.png",
  "💡": "objects/light-bulb-3d.png",
  "🏥": "travel-and-places/hospital-3d.png",
  "✈️": "travel-and-places/airplane-3d.png",
  "🎓": "objects/graduation-cap-3d.png",
  "⚽": "activities/soccer-ball-3d.png",
  "📦": "objects/package-3d.png",
  "☕": "food-and-drinks/hot-beverage-3d.png",
  "🍻": "food-and-drinks/clinking-beer-mugs-3d.png",
  "🎁": "activities/balloon-3d.png",
  "💊": "objects/pill-3d.png",
  "🚕": "travel-and-places/auto-rickshaw-3d.png",
  "🏨": "travel-and-places/hotel-3d.png",
  "👕": "objects/coat-3d.png",
  "💰": "objects/money-bag-3d.png",
  "🎵": "objects/musical-notes-3d.png",
  "📱": "objects/mobile-phone-3d.png",
  "🔧": "objects/hammer-and-wrench-3d.png",
  "💳": "objects/credit-card-3d.png",
  "🧾": "objects/ledger-3d.png",
  "🎮": "activities/video-game-3d.png",
  "📚": "objects/books-3d.png",
  "💄": "objects/lipstick-3d.png",
  "🐶": "objects/shopping-bags-3d.png",
  "🌐": "travel-and-places/globe-with-meridians-3d.png",
  "🍽️": "food-and-drinks/fork-and-knife-with-plate-3d.png",
};

export const isEmojiForKind = (value: string | undefined, kind: EmojiKind) =>
  Boolean(value && (kind === "profile" ? PROFILE_VALUES : OTHER_VALUES).has(value));

export const emojiValue = (value: string | undefined, kind: EmojiKind = "other") => {
  if (value && isEmojiForKind(value, kind)) return value;
  if (kind === "profile") return DEFAULT_PROFILE_EMOJI;
  const legacy =
    value && Object.hasOwn(LEGACY_CATEGORY_IMAGES, value)
      ? LEGACY_CATEGORY_IMAGES[value]
      : undefined;
  return legacy && OTHER_VALUES.has(legacy) ? legacy : DEFAULT_OTHER_EMOJI;
};

export const emojiUrl = (value: string | undefined, kind: EmojiKind = "other") =>
  `${import.meta.env.BASE_URL}emoji-icons/${emojiValue(value, kind)}`;
